# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: qindra-db
    environment:
      POSTGRES_USER: qindra
      POSTGRES_PASSWORD: qindra_pass
      POSTGRES_DB: qindra
    ports:
      - "5432:5432"
    volumes:
      - qindra-data:/var/lib/postgresql/data

volumes:
  qindra-data: